server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    accept-count: 200
    uri-encoding: utf-8
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:D:/work_technology/IdeaWorkSpace/prj-wkcy/db/wyck
    username: admin
    password: 123456
  jpa:
    show-sql: false
#    方言配置
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: false
    database: hsql

